// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package detector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CryptoCryptoEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	CgroupId    uint64
	Pid         uint32
	Tid         uint32
	EventType   uint32
	Confidence  uint32
	AlgoName    [64]int8
	Comm        [16]int8
}

// LoadCrypto returns the embedded CollectionSpec for Crypto.
func LoadCrypto() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CryptoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Crypto: %w", err)
	}

	return spec, err
}

// LoadCryptoObjects loads Crypto and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CryptoObjects
//	*CryptoPrograms
//	*CryptoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCryptoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCrypto()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CryptoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CryptoSpecs struct {
	CryptoProgramSpecs
	CryptoMapSpecs
	CryptoVariableSpecs
}

// CryptoProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CryptoProgramSpecs struct {
	KprobeCryptoAllocAead     *ebpf.ProgramSpec `ebpf:"kprobe_crypto_alloc_aead"`
	KprobeCryptoAllocShash    *ebpf.ProgramSpec `ebpf:"kprobe_crypto_alloc_shash"`
	KprobeCryptoAllocSkcipher *ebpf.ProgramSpec `ebpf:"kprobe_crypto_alloc_skcipher"`
}

// CryptoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CryptoMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	TargetPid *ebpf.MapSpec `ebpf:"target_pid"`
}

// CryptoVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CryptoVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// CryptoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCryptoObjects or ebpf.CollectionSpec.LoadAndAssign.
type CryptoObjects struct {
	CryptoPrograms
	CryptoMaps
	CryptoVariables
}

func (o *CryptoObjects) Close() error {
	return _CryptoClose(
		&o.CryptoPrograms,
		&o.CryptoMaps,
	)
}

// CryptoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCryptoObjects or ebpf.CollectionSpec.LoadAndAssign.
type CryptoMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	TargetPid *ebpf.Map `ebpf:"target_pid"`
}

func (m *CryptoMaps) Close() error {
	return _CryptoClose(
		m.Events,
		m.TargetPid,
	)
}

// CryptoVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCryptoObjects or ebpf.CollectionSpec.LoadAndAssign.
type CryptoVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// CryptoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCryptoObjects or ebpf.CollectionSpec.LoadAndAssign.
type CryptoPrograms struct {
	KprobeCryptoAllocAead     *ebpf.Program `ebpf:"kprobe_crypto_alloc_aead"`
	KprobeCryptoAllocShash    *ebpf.Program `ebpf:"kprobe_crypto_alloc_shash"`
	KprobeCryptoAllocSkcipher *ebpf.Program `ebpf:"kprobe_crypto_alloc_skcipher"`
}

func (p *CryptoPrograms) Close() error {
	return _CryptoClose(
		p.KprobeCryptoAllocAead,
		p.KprobeCryptoAllocShash,
		p.KprobeCryptoAllocSkcipher,
	)
}

func _CryptoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed crypto_bpfeb.o
var _CryptoBytes []byte
